# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 623edde93a5af1e19dbdb808f3063e8d3f7b2f90fcac0e26797c59a6708a0ea284ed91b51750c7c9480c94ff457626cdadeb21b4026ca5698589606dda21ee45

test:
  secret_key_base: 3a6e6b5561f624ec96278e7ef06b38e39a271f2d945b866d002bdf42e34cf08e3d64d3e209b14aa38fdb8c360974e11f7c3e0ce4696bf30d39dfe0ebc18290d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
